config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"

  get "/sign_in" => "sessions#sign_in_form", as: "sign_in"
  post "/sign_in" => "sessions#sign_in"
  delete "/sign_out" => "sessions#sign_out", as: "sign_out"

  resources :users

  resources :profiles
  get "/profiles/:id" => "profiles#upload_avatar", as: "upload_avatar"

  resources :posts do
    resources :comments
  end
  get "/posts/:user_id/posts" => "posts#posts_by_author", as: "posts_by_author"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_attached_file :avatar, styles: { medium: "300x300", thumb: ["100X100", :png] }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  validates :email, presence: true
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :current_user
  before_action :user_authenticated, except: [:new, :create]
  before_action :user_from_nav
  before_action :find_profile_for_avatar, only: [:upload_avatar, :remove_avatar]

  def index
    @profiles = Profile.all
  end

  def show
    @profile = Profile.find(params[:id])
    # @profile = Profile.where(user_id: params[:user_id]).first
    # @user=User.find(@profile.user_id)
  end

  def new
    @profile = Profile.new
  end

  def create
    # puts params.inspect
    @profile=Profile.new(profile_params)
    @profile.user_id=current_user.id
    if @profile.save
      flash[:notice] = "Saved"
      redirect_to user_path(@profile.user_id)
    else
      flash[:alert] = "save failed"
      render :new
    end
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:id])
    @profile.update(profile_params)
    if @profile.save
      flash[:notice] = "Update successful"
      redirect_to user_path(@profile.user_id)
    else
      flash[:alert] = "Update failed"
      redirect_to edit_profile_path(@profile)
    end
  end

  def upload_avatar
    # @profile = Profile.find_by(user_id: params[:user_id])
    @profile.update(@profile.avatar)
    if @profile.save
      flash[:notice] = "Update successful"
      redirect_to user_path(@profile.user_id)
    else
      flash[:alert] = "Update failed"
      redirect_to edit_profile_path(@profile)
    end
  end

  def remove_avatar
    # @profile = Profile.find_by(user_id: params[:user_id])
    @profile.avatar = nil
    @profile.save
  end

  def destroy
    @profile = Profile.find(params[:id])
    if @profile.destroy
      flash[:notice] = "Deleted successfully"
    else
      flash[:alert] = "Delete failed"
    end
    redirect_to profiles_path
  end

  private

  def user_authenticated
    logger.debug ("*** Checking Authenticated User STATUS ***")
    unless session[:user_id]
      flash[:notice] = "Please login."
      redirect_to root_path
    end

    if current_user && current_user.profile.id.to_s != params[:id].to_s
      flash[:alert] = "You do not have access to the requested page."
      redirect_back(fallback_location: root_path)
    end
  end

  def find_profile_for_avatar
    # prev = Rails.application.routes.recognize_path(request.referrer)
    # prev[:controller]
    puts "***  THIS WAS PASSED #{params.inspect} ***"
    identifier = params[:user_id].present? ? "user_id:" : "id:"
    @profile = Profile.find_by(identifier params[:id])
  end

  def profile_params
    params.require(:profile).permit(:email, :fname, :lname, :dob, :avatar, :about, :user_id)
  end
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/profiles/_profile_form.html.erb
<!-- Profiles _profile_form -->

<% if @profile.errors.full_messages.any? %>
<ul>
  <% @profile.errors.full_messages.each do |error_message| %>
  <li>
    <%= error_message %>
  </li>
  <br>
  <% end %>
</ul>
<% end %>
<div class="form-group">
  Email:  <%= f.email_field :email, placeholder: "you@somewhere.com", class: "sign_up #{controller.action_name}-field", readonly: controller.action_name == "show" %>
</div>
<div class="form-group">
  First Name:  <%= f.text_field :fname, placeholder: "First Name", class: "form #{controller.action_name}-field", readonly: controller.action_name == "show" %>
  <% if controller.action_name == "show" %>
    <BR>
  <% end %>
  Last Name:  <%= f.text_field :lname, placeholder: "Last Name", class: "form #{controller.action_name}-field", readonly: controller.action_name == "show" %>
</div>
<div class="form-group">
  DOB:  <%= f.date_field :dob, placeholder: "DOB: MM/DD/YYYY", class: "form #{controller.action_name}-field", readonly: controller.action_name == "show" %>
</div>
<% if controller.action_name == "new" %>
  <BR>
  <div class="form-group">
    <%= f.label(:avatar, "Click to add file", class: "btn btn-secondary avatar-file") %>
    <%= f.file_field :avatar, class: "avatar-file #{controller.action_name}-field", required: true, readonly: controller.action_name == "show" %>
  </div>
<% end %>
<div class="form-group">
  <p>A little about me:</p>
  <%= f.text_area :about, placeholder: "About me", class: "form f_text_area #{controller.action_name}-field", readonly: controller.action_name == "show" %>
</div>

app/views/profiles/_upload_avatar.html.erb
<%= form_for @profile, url: upload_avatar_path, method: :patch, html: {multipart: true} do |avatar_f| %>
  <div class="avatar-file-div">
    <%= avatar_f.label(:avatar, "Click to add file", class: "btn btn-secondary avatar-file") %>
    <%= avatar_f.file_field :avatar, class: "avatar-file", required: true %>
  </div>
  <!-- <hr> -->
  <%= avatar_f.submit "Apply", class: "avatar-file-btn laySignBtn" %>
<% end %>

app/views/profiles/edit.html.erb
<!-- Profiles edit -->

<div class="col-sm-8 blog-main">
  <%= form_for @profile, html: {multipart: true} do |f| %>
      <%= render(partial: "profile_form", locals: {f: f}) %>
      <%= f.submit "Save", class: "save_f" %>
  <% end %>
  <BR>
  <%= link_to("Back", profile_path(@profile.id), class: "btm_links") %>
</div> <!-- /.blog-main -->

app/views/profiles/index.html.erb
<h1>Profile#index</h1>
<p>Find me in app/views/profile/index.html.erb</p>

app/views/profiles/new.html.erb
<!-- Profiles new -->

<div class="col-sm-8 blog-main">
  <%= form_for @profile, url: {action: "create"}, html: {multipart: true} do |f| %>
    <%= render(partial: "profile_form", locals: {f: f}) %>
    <%= f.submit "Save", class: "save_f" %>
  <% end %>
  <BR>
</div> <!-- /.blog-main -->

app/views/profiles/show.html.erb
<!-- Profiles show -->
<!-- <div class="col-sm-8 blog-main"> -->

<div class="col-sm-6 offset-sm-2 blog-main">
  <%= form_for @profile, html: {multipart: true} do |f| %>
    <%= render(partial: "profile_form", locals: {f: f}) %>
  <% end %>
  <BR>
  <% if @current_user && @current_user.id == @profile.user_id %>
    <%= link_to("Edit", edit_profile_path, class: "btm_links") %>
  <% end %>
  <%= link_to("Back", :back, class: "btm_links") %>

</div><!-- /.blog-main -->