config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"

  get "/sign_in" => "sessions#sign_in_form", as: "sign_in"
  post "/sign_in" => "sessions#sign_in"
  delete "/sign_out" => "sessions#sign_out", as: "sign_out"

  resources :users

  resources :profiles
  get "/profiles/:id" => "profiles#upload_avatar", as: "upload_avatar"

  resources :posts do
    resources :comments
  end
  get "/posts/:user_id/posts" => "posts#posts_by_author", as: "posts_by_author"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_one :profile, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  scope :admin, ->{where(:admin, true)}
  before_save { self.username = self.username.to_s.downcase }

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :current_user
  before_action :user_authenticated, except: [:new, :create]
  before_action :user_from_nav
  skip_before_action :user_from_nav, only: [:new, :create]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @profile = Profile.find_by(user_id: @user.id)
  end

  def new
    puts params.inspect
    @user = User.new
  end

  def create
    puts params.inspect
    @user = User.create(user_params)

    if @user.save
      session[:user_id]=@user.id
      redirect_to new_profile_path
    else
      flash[:alert] = "Sign-Up failed"
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
     if @user.update(user_params)
       flash[:notice] = "Update successful"
       redirect_to profile_path(@user.profile.id)
     else
       flash[:alert] = "Update failed"
       render :edit
     end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      session[:user_id] = nil
      flash[:notice] = "Deleted successfully"
      redirect_to root_path
    else
      flash[:alert] = "Delete failed"
      render :back
    end
  end

  private

  def user_authenticated
    logger.debug ("*** Checking Authenticated User STATUS ***")
    unless session[:user_id]
      flash[:notice] = "Please login."
      redirect_to root_path
    end

    if current_user && current_user.id.to_s != params[:id].to_s
      flash[:alert] = "You do not have access to the requested page."
      redirect_back(fallback_location: root_path)
    end
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_edit.html.erb
<!-- User _Edit Form -->

<div class="modal-header">
  <h5 class="modal-title" id="editUserModalLabel">Edit User</h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">×</span>
  </button>
</div>
<div class="modal-body">
  <%= form_for @user do |form| %>
    <% if @user.errors.full_messages.any? %>
    <ul>
      <% @user.errors.full_messages.each do |error_message| %>
      <li>
        <%= error_message %>
      </li>
      <br>
      <% end %>
    </ul>
    <% end %>
    <div class="form-group">
      Username:  <%= form.text_field :username, placeholder: "Username", class: "form-control sign_up" %>
    </div>
    <div class="form-group">
      Password  <%= form.password_field :password, placeholder: "Password", class: "form-control sign_up" %>
    </div>
    <div class="modal-footer">
      <%= form.submit "Save", class: "btn btn-primary" %>
      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    </div>
  <% end %>
</div>

app/views/users/_new.html.erb
<!-- Users _New Form -->

<div class="modal-header">
  <h5 class="modal-title" id="signUpModalLabel">Sign Up</h5>
  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">×</span>
  </button>
</div>
<div class="modal-body">
  <%= form_for @user, url: users_path, method: :create, remote: true, authenticity_token: true, html: {multipart: true} do |f| %>
    <% if @user.errors.full_messages.any? %>
      <ul>
        <% @user.errors.full_messages.each do |error_message| %>
        <li>
          <%= error_message %>
        </li>
        <br>
        <% end %>
      </ul>
    <% end %>
    <div class="form-group">
      Username:  <%= f.text_field :username, placeholder: "Username", class: "form-control sign_up" %>
    </div>
    <div class="form-group">
      Password  <%= f.password_field :password, placeholder: "Password", class: "form-control sign_up" %>
    </div>
    <div class="modal-footer">
      <%= f.submit "Save", class: "btn btn-primary" %>
      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<!-- User Edit Form -->

<%= form_for @user do |form| %>
  <% if @user.errors.full_messages.any? %>
  <ul>
    <% @user.errors.full_messages.each do |error_message| %>
    <li>
      <%= error_message %>
    </li>
    <br>
    <% end %>
  </ul>
  <% end %>
  <div class="form-group">
    Username:  <%= form.text_field :username, placeholder: "Username", class: "form-control sign_up" %>
  </div>
  <div class="form-group">
    Password  <%= form.password_field :password, placeholder: "Password", class: "form-control sign_up" %>
  </div>
    <%= form.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>
<BR>
<%= link_to("Back", :back, class: "btm_links") %>

app/views/users/edit.js.erb
// Show Modal in Users _Edit
$("#userEditModal .modal-content").html('<%= j render "users/edit" %>');

app/views/users/index.html.erb
<!-- users/index.html.erb -->
<div class="col-sm-8">

<ul>
<% @users.each do |user| %>
  <li>
    <%= link_to("Show #{user.username.capitalize}", user_path(user)) %>
    <%= link_to("Edit", edit_user_path(user), method: :edit) %>
    <%= link_to("Delete", user_path(user), method: :delete) %>
  </li>
<% end %>
</ul>

<%= link_to("New User", new_user_path) %>

</div>

app/views/users/new.html.erb
<!-- User New Form -->

<%= form_for @user, url: users_path, method: :create, remote: true, authenticity_token: true, html: {multipart: true} do |f| %>
  <% if @user.errors.full_messages.any? %>
    <ul>
      <% @user.errors.full_messages.each do |error_message| %>
      <li>
        <%= error_message %>
      </li>
      <br>
      <% end %>
    </ul>
  <% end %>
  <div class="form-group">
    Username:  <%= f.text_field :username, placeholder: "Username", class: "form-control sign_up" %>
  </div>
  <div class="form-group">
    Password  <%= f.password_field :password, placeholder: "Password", class: "form-control sign_up" %>
  </div>
  <div class="modal-footer">
    <%= f.submit "Save", class: "btn btn-primary" %>
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
  </div>
<% end %>

app/views/users/new.js.erb
// Show Modal in Users _New
$("#signUpModal .modal-content").html('<%= j render "users/new" %>');

app/views/users/show.html.erb
<!-- users/show.html.erb -->
<!-- <div class="col-sm-8 blog-main"> -->

<div class="col-sm-6 offset-sm-2 blog-main">

  <p><span class="post_t">Username: </span><%=@user.username %></p>
  <BR>
  <p><span class="post_t">Password: ********** </span></p>
  <BR>
    <p><span class="post_t">Email:   </span><%=@user.profile.email %></p>
  <BR>
  <p><span class="post_t">First Name:  </span><%=@user.profile.fname %></p>
  <p><span class="post_t">Last Name:  </span><%=@user.profile.lname %></p>
  <BR>
  <span class="post_t">A little about me: </span>
  <p class="post"> <%= @user.profile.about %></p>
  <BR>
  <% if @current_user && @current_user.id == @user.profile.user_id %>
    <%= link_to("Edit", edit_profile_path(@user.profile.id), class: "btm_links") %>
  <% end %>
  <%= link_to("Back", :back, class: "btm_links") %>

</div><!-- /.blog-main -->