config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"

  get "/sign_in" => "sessions#sign_in_form", as: "sign_in"
  post "/sign_in" => "sessions#sign_in"
  delete "/sign_out" => "sessions#sign_out", as: "sign_out"

  resources :users

  resources :profiles
  get "/profiles/:id" => "profiles#upload_avatar", as: "upload_avatar"

  resources :posts do
    resources :comments
  end
  get "/posts/:user_id/posts" => "posts#posts_by_author", as: "posts_by_author"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: { maximum: 100 }

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :current_user
  before_action :user_from_nav

  def index
    @posts = Post.order('created_at DESC').all
  end
  #
  # def my_post
  #   @posts=Post.where(user_id: params[:user_id])
  # end

  def posts_by_author
    @posts=Post.where(user_id: params[:user_id]).reverse
    @author = current_user && current_user.id.to_s == params[:user_id] ? "My Posts" : "#{User.find(params[:user_id]).username.capitalize}'s Posts"
  end

  def show
    @post=Post.find(params[:id])
    # @comments_by_post=Comment.where(params[:id])
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    puts params.inspect
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      flash[:notice] = "Saved"
      redirect_to post_path(@post)
    else
      render "new"
    end
  end

  def update
    @post = Post.find(params[:id])
     if @post.update(post_params)
       flash[:notice] = "Update successful"
       redirect_to post_path(@post)
     else
       flash[:alert] = "Update failed"
       render "edit"
     end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      flash[:notice] = "Deleted successfully"
    else
      flash[:alert] = "Delete failed"
    end
      redirect_to posts_path(@post)
  end

  private

  # def generate_class
  #   comments-css= [
  #       "shade",
  #       "no-shade",
  #     ];
  #
  #   comments-element=[]
  #   cnt=Flavor.all.length
  #   comments-css.cycle(cnt) do |c|
  #     comments-element.push(c)
  #     @cnt=1
  #   end
  # end

  def post_params
    params.require(:post).permit(:title, :content, :user_id)
  end
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/posts/_all_posts.html.erb
<% @posts.each do |post| %>
  <div class="blog-post">
    <h2 class="blog-post-title"><%= post.title %></h2>
    <p class="blog-post-meta"><%= post.created_at.strftime("%B %d, %Y") %>
      <% if controller.action_name == "index" %>
       <span class="blog-post-meta"> by <%= link_to("#{post.user.username.capitalize}", posts_by_author_path(post.user_id), method: :get, class: "post-user-link") %></span>
      <% end %>
    </p>
    <blockquote>
      <%= post.content %>
    </blockquote>
    <p>
      <% if @current_user %>
        <%= content_tag (:span), data: {toggle: "tooltip", placement: "top", title: "New Comment"} do %>
          <%= link_to new_post_comment_path(post), class: "m-3 post_links", data: {remote: true, toggle: "modal", target: "#newCommentModal"} do %>
            <i class="fa fa-comment-o" aria-hidden="true"></i>
          <% end %>
        <% end %>
      <% end %>
      <%= content_tag (:span), data: {toggle: "tooltip", placement: "top", title: "See Comments"} do %>
        <%= link_to "#comment_div_#{post.id}", id: "show-comments-link", data: {toggle: "collapse"} do %>
          <%= post.comments.all.length %>
        <% end %>
      <% end %>
      <% if @current_user && (@current_user.id == post.user_id || @current_user.admin) %>
        <%= content_tag (:span), data: {toggle: "tooltip", placement: "top", title: "Edit Post"} do %>
          <%= link_to edit_post_path(post.id), class: "m-3 post_links", data: {remote: true, toggle: "modal", target: "#editPostModal"} do %>
            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
          <% end %>
        <% end %>
        <%= link_to post_path(post.id), method: :delete, data: { confirm: 'Are you sure you want to delete this post?' }, class: "m-3 post_links" do %>
          <i class="fa fa-trash-o" aria-hidden="true"></i>
        <% end %>
      <% end %>
    </p>
    <div id="comment_div_<%= post.id %>" class="post-comments-div collapse">
      <% post.comments.each do |comment| %>
        <%= image_tag comment.user.profile.avatar.url(:thumb), class: "commenter-avatar js-action-profile-avatar" %>
        <span><%= link_to("#{comment.user.username.capitalize}", posts_by_author_path(comment.user_id), method: :get, class: "post-user-link") %></span>
        <p class="blog-post-meta"><%= comment.created_at.strftime("%b %d '%y %I:%M %p") %></p>
        <section  class="post-comments-section">
          <blockquote class="post-comments-quote">
            <%= comment.content %>
          </blockquote>
          <p>
            <% if @current_user && (@current_user.id == comment.user_id || @current_user.admin) %>
              <%= content_tag (:span), data: {toggle: "tooltip", placement: "top", title: "Edit Comment"} do %>
                <%= link_to edit_post_comment_path(comment.post, comment), class: "m-3 post_links", data: {remote: true, toggle: "modal", target: "#editCommentModal"} do %>
                  <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                <% end %>
              <% end %>
              <%= link_to post_comment_path(comment.post, comment), method: :delete, data: { confirm: 'Delete comment?' }, class: "m-3 post_links" do %>
               <i class="fa fa-trash-o" aria-hidden="true"></i>
              <% end %>
            <% end %>
          </p>
      </section>
      <% end %>
    </div>
  </div><!-- /.blog-post -->
<% end %>

app/views/posts/_edit.html.erb
<!--  COMING FROM _EDIT -->

  <div class="modal-header">
    <h5 class="modal-title" id="editPostModalLabel">Edit Post</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">×</span>
    </button>
  </div>
  <div class="modal-body">
    <%= render "post_form" %>
  </div>

app/views/posts/_new.html.erb
<!--  COMING FROM _NEW -->

  <div class="modal-header">
    <h5 class="modal-title" id="newPostModalLabel">What's new?</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">×</span>
    </button>
  </div>
  <div class="modal-body">
    <%= render "post_form" %>
  </div>

app/views/posts/_post_form.html.erb
  <%= form_for @post do |form| %>
    <% if @post.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@post.errors.count, "error") %> prohibited
          this post from being saved:
        </h2>
        <ul>
          <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-group">
      <%= form.label :title, class: "post-label" %>
      <%= form.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.text_area :content, id: "froala-editor", class: "form-control" %>
    </div>
    <div class="modal-footer">
      <%= form.submit "Save", class: "btn btn-primary" %>
      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    </div>
  <% end %>

app/views/posts/_shared_links.html.erb
<!--  Posts _shared_links -->
<!--  available based on controller, user, and role  -->

<!-- Links only available to logged-in users.  Not shown on index views-->
<% if @current_user && controller.action_name != "index" %>
  <%= content_tag (:span), data: {toggle: "tooltip", placement: "top", title: "New Comment"} do %>
    <%= link_to new_post_comment_path(post), class: "m-3 post_links", data: {remote: true, toggle: "modal", target: "#newCommentModal"} do %>
      <i class="fa fa-comment-o" aria-hidden="true"></i>
    <% end %>
  <% end %>
<% end %>


<!-- Links only available to lall users -->
<%= content_tag (:span), data: {toggle: "tooltip", placement: "top", title: "See Comments"} do %>
  <%= link_to "#comment_div_#{@post.id}", id: "show-comments-link", data: {toggle: "collapse"} do %>
    <%= @post.comments.all.length %>
  <% end %>
<% end %>

<!-- Links only available to the post author or Admin when logged-in-->
<% if @current_user && @current_user.id == @post.user_id || @current_user.admin %>
  <%= content_tag (:span), data: {toggle: "tooltip", placement: "top", title: "Edit Post"} do %>
    <%= link_to edit_post_path(@post.id), class: "m-3 post_links", data: {remote: true, toggle: "modal", target: "#editPostModal"} do %>
      <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
    <% end %>
  <% end %>
  <%= link_to post_path(@post.id), method: :delete, data: { confirm: 'Are you sure you want to delete this post?' }, class: "m-3 post_links" do %>
    <i class="fa fa-trash-o" aria-hidden="true"></i>
  <% end %>
<% end %>

app/views/posts/_show.html.erb
<!-- _Show post -->

<!-- Post Show Comments -->
<p>
<span class="post_t">Comments:</span>
</p>
<% @post.comments.each do |comment| %>
  <p class="post"><%= comment.content %></p>
  <% if @current_user && @current_user.id == comment.user_id %>
    <%= link_to("Delete", [comment.post, comment], method: :delete, data: { confirm: 'Delete comment?' }, class: "m-3 post_links") %>
  <% end %>
  <BR>
<% end %>
<% if @current_user %>
  <span class="post_t">Add a Comment:</span>
  <%= render "comments/comment_form" %>
<% end %>


<!--  -----------------------------------------------   -->

<% @post.comments.each do |comment| %>
  <blockquote>
    <%= comment.content %>
  </blockquote>
  <% if @current_user && @current_user.id == comment.user_id %>
    <%= content_tag (:span), data: {toggle: "tooltip", placement: "top", title: "Edit Post"} do %>
      <%= link_to edit_post_path(@post.id), class: "m-3 post_links", data: {remote: true, toggle: "modal", target: "#editPostModal"} do %>
        <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
      <% end %>
    <% end %>
    <%= link_to("Delete", [comment.post, comment], method: :delete, data: { confirm: 'Delete comment?' }, class: "m-3 post_links")  do %>
      <i class="fa fa-trash-o" aria-hidden="true"></i>
    <% end %>
  <% end %>
<% end %>

app/views/posts/edit.html.erb
<!-- Edit post form from Edit -->

<h1>Edit Post</h1>
<%= render "post_form" %>

app/views/posts/edit.js.erb
// Show Modal in _edit
$("#editPostModal .modal-content").html('<%= j render "posts/edit" %>');

app/views/posts/index.html.erb
<!--  Posts index -->

<div class="col-sm-8 blog-main">
  <h2>All Posts</h2>
  <%= render "posts/all_posts" %>
</div> <!-- /.blog-main -->

app/views/posts/new.html.erb
<!-- New post form from new -->

<div class="col-sm-8 blog-main">
<%= render "post_form" %>
</div> <!-- /.blog-main -->

app/views/posts/new.js.erb
// Show Modal in _new
$("#newPostModal .modal-content").html('<%= j render "posts/new" %>');

app/views/posts/posts_by_author.html.erb
<!--  Posts post_by_author -->

<div class="col-sm-8 blog-main">
  <h2><%= @author %></h2>
  <%= render "posts/all_posts" %>
</div> <!-- /.blog-main -->

app/views/posts/show.html.erb
<!-- Show post -->

<div class="col-sm-8 blog-main">
  <div class="blog-post">
    <h2 class="blog-post-title"><%= @post.title %></h2>
    <p class="blog-post-meta"><%= @post.created_at.strftime("%B %d, %Y") %></p>
    <blockquote>
      <%= @post.content %>
    </blockquote>
    <p>
      <% if @current_user %>
        <%= content_tag (:span), data: {toggle: "tooltip", placement: "top", title: "New Comment"} do %>
          <%= link_to new_post_comment_path(@post), class: "m-3 post_links", data: {remote: true, toggle: "modal", target: "#newCommentModal"} do %>
            <i class="fa fa-comment-o" aria-hidden="true"></i>
          <% end %>
        <% end %>
      <% end %>
      <%= content_tag (:span), data: {toggle: "tooltip", placement: "top", title: "See Comments"} do %>
        <%= link_to "#comment_div_#{@post.id}", id: "show-comments-link", data: {toggle: "collapse"} do %>
          <%= @post.comments.all.length %>
        <% end %>
      <% end %>
      <% if @current_user && @current_user.id == @post.user_id || @current_user.admin %>
        <%= content_tag (:span), data: {toggle: "tooltip", placement: "top", title: "Edit Post"} do %>
          <%= link_to edit_post_path(@post.id), class: "m-3 post_links", data: {remote: true, toggle: "modal", target: "#editPostModal"} do %>
            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
          <% end %>
        <% end %>
        <%= link_to post_path(@post.id), method: :delete, data: { confirm: 'Are you sure you want to delete this post?' }, class: "m-3 post_links" do %>
          <i class="fa fa-trash-o" aria-hidden="true"></i>
        <% end %>
      <% end %>
      <%= link_to("Back", :back, class: "m-3 post_links") %>
    </p>
    <div id="comment_div_<%= @post.id %>" class="post-comments-div collapse">
      <% @post.comments.each do |comment| %>
        <%= image_tag comment.user.profile.avatar.url(:thumb), class: "commenter-avatar js-action-profile-avatar" %>
        <span><%= link_to("#{comment.user.username.capitalize}", posts_by_author_path(comment.user_id), method: :get, class: "post-user-link") %></span>
        <p class="blog-post-meta"><%= comment.created_at.strftime("%b %d '%y %I:%M %p") %></p>
        <section  class="post-comments-section">
          <blockquote class="post-comments-quote">
            <%= comment.content %>
          </blockquote>
          <p>
            <% if @current_user && (@current_user.id == comment.user_id || @current_user.admin) %>
              <%= content_tag (:span), data: {toggle: "tooltip", placement: "top", title: "Edit Comment"} do %>
                <%= link_to edit_post_comment_path(comment.post, comment), class: "m-3 post_links", data: {remote: true, toggle: "modal", target: "#editCommentModal"} do %>
                  <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                <% end %>
              <% end %>
              <%= link_to post_comment_path(comment.post, comment), method: :delete, data: { confirm: 'Delete comment?' }, class: "m-3 post_links" do %>
               <i class="fa fa-trash-o" aria-hidden="true"></i>
              <% end %>
            <% end %>
          </p>
      </section>
      <% end %>
    </div>
  </div><!-- /.blog-post -->
</div> <!-- /.blog-main -->