config/routes.rb
Rails.application.routes.draw do

  root to: "home#index"

  get "/sign_in" => "sessions#sign_in_form", as: "sign_in"
  post "/sign_in" => "sessions#sign_in"
  delete "/sign_out" => "sessions#sign_out", as: "sign_out"

  resources :users

  resources :profiles
  get "/profiles/:id" => "profiles#upload_avatar", as: "upload_avatar"

  resources :posts do
    resources :comments
  end
  get "/posts/:user_id/posts" => "posts#posts_by_author", as: "posts_by_author"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_modals.html.erb
<!-- signUpModal skeleton -->
<div class="modal fade" id="signUpModal" tabindex="-1" role="dialog" aria-labelledby="signUpModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
    </div>
  </div>
</div>

<!-- newPostModal skeleton -->
<div class="modal fade" id="newPostModal" tabindex="-1" role="dialog" aria-labelledby="newPostModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
    </div>
  </div>
</div>

<!-- editPostModal skeleton -->
<div class="modal fade" id="editPostModal" tabindex="-1" role="dialog" aria-labelledby="editPostModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
    </div>
  </div>
</div>

<!-- newCommentModal skeleton -->
<div class="modal fade" id="newCommentModal" tabindex="-1" role="dialog" aria-labelledby="newCommentModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
    </div>
  </div>
</div>

<!-- editCommentModal skeleton -->
<div class="modal fade" id="editCommentModal" tabindex="-1" role="dialog" aria-labelledby="editCommentModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
    </div>
  </div>
</div>

<!-- <%= controller.action_name %><%= controller.controller_name.capitalize %>Modal skeleton -->
<div class="modal fade" id="<%= controller.action_name %><%= controller.controller_name.capitalize %>Modal" tabindex="-1" role="dialog" aria-labelledby="<%= controller.action_name %><%= controller.controller_name.capitalize %>Label" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
    </div>
  </div>
</div>

app/views/layouts/_navbar_no_session.html.erb
<ul class="nav nav-tabs nav-justified">
  <li class="nav-item">
    <%= link_to("Home", root_path, id: "logo", class: "navbar-brand nav-link") %>
  </li>
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
       <small>Have an account?</small> <span class="emphasize"> Log in</span><span class="caret"></span>
    </a>
    <div class="dropdown-menu dropdown-menu-right">
      <div class="signin-dialog-body dropdown-item">
        <div>Have an account?</div>
          <%= render "sessions/sign_in_form" %>
          <hr>
          <div class="signup SignupForm">
            <div class="SignupForm-header">New fish in the bowl?</div>
              <%= link_to("Sign Up", new_user_path, id: "lay_up", class: "laySignBtn", data: {remote: true, toggle: "modal", target: "#signUpModal"}) %>
          </div>
      </div>
    </div>
  </li>
</ul>

app/views/layouts/_navbar_session.html.erb
<ul class="nav nav-tabs nav-justified">
  <li class="nav-item">
    <%= link_to(" ", root_path, id: "logo", class: "navbar-brand nav-link #{controller.controller_name}") %>
  </li>
  <li class="nav-item">
    <%= link_to("My Post", posts_by_author_path(current_user.id), method: :get, class: "nav-link lay_drop_lnks") %>
  </li>
  <li class="nav-item">
    <%= link_to("New Post", new_post_path, method: :get, class: "nav-link lay_drop_lnks") %>
  </li>

  <li class="nav-item dropdown">
    <a id="dropdownMain" class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
       <small>Logged in as</small> <span class="emphasize"><%= current_user.username.capitalize %></span><span class="caret"></span>
    </a>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMain">
      <% if current_user.profile %>
        <%= link_to("Profile", profile_path(current_user.profile.id), method: :get, class: "dropdown-item lay_drop_lnks") %>
      <% end %>
      <%= link_to("My Post", posts_by_author_path(current_user.id), method: :get, class: "dropdown-item lay_drop_lnks") %>
      <%= link_to("New Post", new_post_path, method: :get, class: "dropdown-item lay_drop_lnks") %>
      <div class="dropdown dropdown-item">
        <a id="dropdownMenu2" class="dropdown-toggle lay_drop_lnks" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
           <span>Change Password </span><span class="caret"></span>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu2">
          <div class="signin-dialog-body dropdown-item lay_drop_lnks">
            <%= render "users/edit" %>
          </div>
        </div>
      </div>
      <%= link_to("Delete Account", user_path(current_user), method: :delete, data: {confirm: "Are you sure you want to delete account?"}, class: "dropdown-item lay_drop_lnks") %>
      <hr>
      <%= link_to("Sign Out", sign_out_path, method: :delete, class: "dropdown-item lay_drop_lnks laySignBtn") %>
    </div>
  </li>
</ul>

app/views/layouts/_profile_aside.html.erb
<!--  profile_aside -->
<div class="col-sm-4">
  <% if current_user.profile %>

  <div class="card sidebar-module sidebar-module-inset profile-card-cap">
  <!-- <div class="card" style="width: 20rem;"> -->
    <div class="card-img-top"></div>
    <div class="avatar-div">
      <!-- Will show preview image when a new image is selected -->
      <img class="avatar-preview">
      <!--  Stored profile image -->
      <%= image_tag @user.profile.avatar.url(:thumb), class: "avatar js-action-profile-avatar" %>
    </div>
    <div class="dropdown avatar-drop-div">
      <a class="avatar-drop-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
         <span class="caret"></span>
      </a>
      <div class="dropdown-menu">
        <div class="dropdown-item avatar-form-div">

            <%= render "profiles/upload_avatar" %>

        </div>
      </div>
    </div>
    <span><%= link_to("#{@user.username.capitalize}", posts_by_author_path(@user.id), method: :get, class: "post-user-link") %></span>
  </div>
  <% end %>

</div> <!-- /.profile-aside -->

app/views/layouts/_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>About</h4>
    <p>The FishBowl is a safe place to blog and find your <em>shoal</em> in an ocean of internet sharks.  Join or create your own bowl.  Invite others to come swim with you.</p>
  </div>
  <div class="sidebar-module">
    <h4>Archives</h4>
    <ol class="list-unstyled">
      <li><a href="#">March 2014</a></li>
      <li><a href="#">February 2014</a></li>
      <li><a href="#">January 2014</a></li>
      <li><a href="#">December 2013</a></li>
      <li><a href="#">November 2013</a></li>
      <li><a href="#">October 2013</a></li>
      <li><a href="#">September 2013</a></li>
      <li><a href="#">August 2013</a></li>
      <li><a href="#">July 2013</a></li>
      <li><a href="#">June 2013</a></li>
      <li><a href="#">May 2013</a></li>
      <li><a href="#">April 2013</a></li>
    </ol>
  </div>
  <div class="sidebar-module">
    <h4>Elsewhere</h4>
    <ol class="list-unstyled">
      <li><a href="#">GitHub</a></li>
      <li><a href="#">Twitter</a></li>
      <li><a href="#">Facebook</a></li>
    </ol>
  </div>
</div> <!-- /.blog-sidebar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FishBowl</title>
    <link rel="shortcut icon" href="<%=asset_path("favicon.ico")%>" type="image/x-icon">
    <%= csrf_meta_tags %>
    <meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Indie+Flower|Lobster|Lobster+Two" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--  Icons -->
    <script src="https://use.fontawesome.com/144ed3a5c7.js"></script>
  </head>

  <body>

    <div id="lay-nav" class="fixed-top blog-masthead">
        <% if @current_user.nil? %>
          <%= render "layouts/navbar_no_session" %>
        <% else %>
          <%= render "layouts/navbar_session" %>
        <% end %>
    </div>

    <header class="<%= controller.controller_name %>-<%= controller.action_name %>-header">
      <% if flash[:notice] %>
        <div id="notice">
          <%= flash[:notice] %>
        </div>
      <% end %>
      <% if flash[:alert] %>
        <div id="alert">
          <%= flash[:alert] %>
        </div>
      <% end %>
    </header>

    <div class="sticky blog-header <%= controller.controller_name %>-no-blog-header">
      <div class="container">
        <h1 class="blog-title">Fishbowl</h1>
        <p class="lead blog-description">A little blog for a big world.</p>
      </div>
    </div>

    <div class="container <%= controller.controller_name %>-container <%= controller.controller_name %>-<%= controller.action_name %>-container">
      <div class="row">

        <% if controller.controller_name == "users" || controller.controller_name == "profiles" %>
          <%= render "layouts/profile_aside" %>
        <% end %>

        <%= yield %>
        <%= render "layouts/modals" %>

        <% if controller.controller_name == "home" || controller.controller_name == "posts" || controller.controller_name == "comments" %>
          <%= render "layouts/sidebar" %>
        <% end %>

      </div> <!-- /.row -->
    </div> <!-- /.container -->

    <footer class="blog-footer">
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>
  </body>
</html>